# Generated by Django 3.1.5 on 2021-02-12 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=30, verbose_name='방문매장')),
                ('visited_date', models.DateTimeField(verbose_name='방문일자')),
                ('customers', models.CharField(default='가족', max_length=30, verbose_name='동반고객')),
                ('satisfaction', models.PositiveIntegerField(default=5, verbose_name='만족도')),
                ('title', models.CharField(default='제목', max_length=128, verbose_name='제목')),
                ('content', models.TextField(default='내용', verbose_name='내용')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='추천수')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성 시간')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='수정 시간')),
                ('upload_files', models.ImageField(blank=True, null=True, upload_to='', verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
