# Generated by Django 3.1.5 on 2021-02-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('r_si', models.CharField(max_length=10)),
                ('r_gu', models.CharField(max_length=10)),
                ('r_name', models.TextField()),
                ('r_address', models.TextField()),
            ],
        ),
    ]
