# Generated by Django 3.1.5 on 2021-02-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=30, verbose_name='방문매장')),
                ('satisfaction', models.PositiveIntegerField(default=5, verbose_name='만족도')),
                ('title', models.CharField(default='제목', max_length=128, verbose_name='제목')),
                ('content', models.TextField(default='내용', verbose_name='내용')),
            ],
        ),
    ]
