# Generated by Django 3.1.5 on 2021-02-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='likes_user',
        ),
    ]
