# Generated by Django 3.1.5 on 2021-02-17 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0002_remove_board_likes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='likes_user',
            field=models.ManyToManyField(blank=True, related_name='likes_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
