# Generated by Django 3.1.5 on 2021-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_board_likes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='mainphoto',
            field=models.ImageField(default=0, upload_to='', verbose_name='사진'),
        ),
    ]
